### ISSUE TITLE
Stackoverflow data research

### ISSUE THREAD

**Issue by oferb** [hasadna/hasadna#49]
Since we don't know the Stackoverflow data (yet), this is a preliminary research task.
Stackoverflow data is either in a website:
https://archive.org/download/stackexchange

Or in downloadable files:
https://data.stackexchange.com/stackoverflow/queries

The task is to find a way to get "technology trends" by location (e.g Israel) and by time (e.g last quarter to this quarter).
We don't know if the information is there and in what form, so this is an investigation task 🕵️.

**Comment by mohammad-suliman** [comment]
### Background:
the stackexchange is a question and answer platform which allows the users to post their questions and get answers in many different topics. the stackexchange platform has around 174 sites, every site is dedicated to one topic. the most famous site in this family is the stackoverflow site, especially among programmers, I think that this site will get the main focus in this project, however, there are other sites which are technology related, such as:
- android: a site for question and answer for android enthusiasts.
- apple: a site for discussing apple's software and hardware products.
and so on... it is not clear to me whether we will only deal with stackoverflow, or with other technology related sites also.
### actual results:
in most cases each site has 8 xml files, the most important files for us is:
- posts.xml: this file shows the posts for each site in the family, each post has several fields, the most important fields for us is:
  - id 
  - type: post type, this is a numeric field, which gets values from 1 - 9.
  - creationDate
  - tags: this field is optional. in stackoverflow, it allows us to determine the technology domain for the question; html, java c#, and so on...
  - OwnerUserId, the id of the user who created the post, this will help us to link it to the user entry in the users.xml file to get the user's location.
- users.xml file; this file includes the users's data, the most important fields for us:
  - id
  - location, this field seams to be optional i believe, but from the sample i manage to read from the users.xml file for stackoverflow site, most users have mentioned their location. not sure that this is the case for most users.
a note about this field: haven't been able to find a consistent format for this field; some times it includes the state only, some times it includes the country only, and some times it includes both. so this will be a challenge for future work I think.
- tags.xml file; this file includes the different tags which can be used in the site. as I have mentioned earlier, the tag can help us determine the technology type for the question in stackoverflow, not sure it helps for other sites if we choose to include them in the project.
### additional links and questions:
- haven't been able to download the stackoverflow-s posts.xml file because it's a 12 GB file when compressed. I don't know whether we can use it in the project in the future when it is so large as this. an alternative to this might be to use an API to get the data, this API is available, here is the link:
https://api.stackexchange.com/docs
- haven't played much with the data available in the website you linked to, it needs SQL knowledge, and I am not expert in this field:) also this website is intended to be used by humans, and not by code, as it requires solving a CAPTCHA.

**Comment by mohammad-suliman** [comment]
### additional links and questions continued:
- a link for short documentation for the XML tables of stackexchange sites:
https://meta.stackexchange.com/questions/2677/database-schema-documentation-for-the-public-data-dump-and-sede
it seams that this is the only documentation available.
- the last question/concern; are we going to include data from sites other than stackoverflow, especially sites which are technology related? or we only are going to deal with stackoverflow?

**Comment by oferb** [comment]
> it is not clear to me whether we will only deal with stackoverflow, or with other technology related sites also
We will focus on Stackoverflow. Other sites are interesting, but are much smaller, and our main goal is to understand programming technology trends.
> so this will be a challenge for future work I think.

**Comment by oferb** [comment]
Great job Mohammad! You can close the issue :)

**Comment by mohammad-suliman** [comment]
thanks so much Ofer, closing as requested
